# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/nano enhanced/nanporocessor/nanporocessor.srcs/sources_1/ip/program_counter_new/program_counter_new.xci
# IP: The module: 'program_counter_new' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nano enhanced/nanporocessor/nanporocessor.srcs/sources_1/ip/program_counter_new/program_counter_new_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_counter_new'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/nano enhanced/nanporocessor/nanporocessor.srcs/sources_1/ip/program_counter_new/program_counter_new.xci
# IP: The module: 'program_counter_new' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nano enhanced/nanporocessor/nanporocessor.srcs/sources_1/ip/program_counter_new/program_counter_new_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_counter_new'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
